#ifndef CONSTEXPRCORE_PERFECT_HASH_VERSION_H
#define CONSTEXPRCORE_PERFECT_HASH_VERSION_H

// Generated by tools/release.py — edit that script, not these numbers.
#define CONSTEXPRCORE_PERFECT_HASH_VERSION "0.2.0"
#define CONSTEXPRCORE_PERFECT_HASH_VERSION_MAJOR 0
#define CONSTEXPRCORE_PERFECT_HASH_VERSION_MINOR 2
#define CONSTEXPRCORE_PERFECT_HASH_VERSION_REVISION 0

namespace ConstexprCore {
// Version of the library, as "major.minor.revision".
inline constexpr const char* perfect_hash_version = CONSTEXPRCORE_PERFECT_HASH_VERSION;
inline constexpr int perfect_hash_version_major = CONSTEXPRCORE_PERFECT_HASH_VERSION_MAJOR;
inline constexpr int perfect_hash_version_minor = CONSTEXPRCORE_PERFECT_HASH_VERSION_MINOR;
inline constexpr int perfect_hash_version_revision = CONSTEXPRCORE_PERFECT_HASH_VERSION_REVISION;
} // namespace ConstexprCore

#endif // CONSTEXPRCORE_PERFECT_HASH_VERSION_H
